### ISSUE TITLE
Cannot parse UTF-8 with BOM files

### ISSUE THREAD

**Issue by kyle-rader-msft** [TheDaemoness/ec4rs#10]
Attempting to parse a valid EditorConfig file that has a UTF-8 [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) results in an `ec4rs::Error` of "invalid line".

This is an issue that should be handled early on in the IO. In our consuming project we handle files of ASCII, UTF-8, UTF-8-BOM, UTF-16-[BE|LE] by having our own small `FileContent` abstraction. Something similar may be useful here/there may be a crate for this already but we didn't fine a simple one we liked and it's not much code.

I can work on contributing a fix for this soon.

**Comment by kyle-rader-msft** [comment]
Very interesting. So I was able to open source https://github.com/microsoft/file-content-rs 2 weeks ago, and now as I'm writing integration tests for utf8 and utf-8-bom, I find that my own test does pass already as is, for utf-8-bom... We were seeing failures in our linter calling `properties_of` on files, who had ec files with a BOM in their parent tree. Saving those files as UTF-8 (no BOM) resolved the issue.

I'll see if I can repro that again.

**Comment by kyle-rader-msft** [comment]
I'm thoroughly confused as to what I saw. utf-8-bom defintely works. If interested, file-content can make it easy to get files as Strings, from utf-16[le|be], though this is far less common so it's not something I'll pursue right now.

**Comment by BaumiCoder** [comment]
> @kyle-rader-msft  wrote:
> ...
> I'll see if I can repro that again.

I am able to reproduce that bug. I encounter it with two `.editorconfig` files in two projects, which are UTF-8 encoded with BOM. Furthermore, I made a small example project for reproduction. It calls `ec4rs::properties_of` on a given file and contains the two mentioned projects as git submodules. More details are in the README there:

https://github.com/BaumiCoder/ec4rs_BOM_test

Therefore, I think this issue should be reopened, but I do not have the permission to do so.

**Comment by TheDaemoness** [comment]
I found a testcase that reproduces the bug. Specifically, the following test was failing with a `ParseError::InvalidLine`:
https://github.com/TheDaemoness/ec4rs/blob/a23a36bfa3e713e51e8d43bd88c34a0cf11499b7/src/parser/tests.rs#L111

This is now fixed as of https://github.com/TheDaemoness/ec4rs/commit/a23a36bfa3e713e51e8d43bd88c34a0cf11499b7.
